INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Brasília','2h30m',500.00);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Rio de Janeiro','1h30m',350.50);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Porto Alegre','3h',700.25);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Recife','4h15m',900.75);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Salvador','3h45m',800.00);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Florianópolis','2h',450.50);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Manaus','5h30m',1200.00);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Fortaleza','4h',950.25);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Goiania','1h45m',400.75);
INSERT INTO tb_passagem (partida, chegada, duracao, preco) VALUES ('São Paulo - Guarulhos','Curitiba','1h15m',300.50);

INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Ana Silva','123.456.789-01',1);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Carlos Oliveira','987.654.321-02',10);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Maria Souza','111.222.333-44',1);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('João Santos','555.666.777-88',2);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Gulherme Souza','222.666.777-88',2);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Rafael Lima','777.888.999-00',7);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Pedro Oliveira','666.555.444-33',5);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Pedro Oliveira','666.555.444-33',1);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Roberto Silva','333.222.111-00',5);
INSERT INTO tb_cliente (nome, cpf, passagem_id) VALUES ('Gustavo','111.234.267-09',10);
